// Generated by gulp icon - do not modify manually
import React from "react";

export interface IconProps {
    color?: string;
    className?: string;
    onClick?: () => void;
    style?: any;
}

export default class Icon extends React.Component<IconProps, {}> {
    static defaultProps = {
        style: {},
        className: "",
        color: "currentColor",
        onClick: () => {},
    };

    render() {
        const { color, onClick, style, className } = this.props;
        return (
            <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                fill={color}
                onClick={onClick}
                style={style}
                className={className}
                width="1em"
                height="1em"
                viewBox="0 0 16 16"
            >
                <defs>
                    <path id="a" d="M0 0h16v16H0z" />
                </defs>
                <g>
                    <mask id="b">
                        <use xlinkHref="#a" />
                    </mask>
                    <path
                        d="M8 2.167a5.834 5.834 0 1 0 0 11.667A5.834 5.834 0 0 0 8 2.167ZM8 1a7 7 0 1 1-.001 14.001A7 7 0 0 1 8 1Z"
                        mask="url(#b)"
                    />
                    <path
                        stroke="currentColor"
                        strokeWidth=".2"
                        d="M7.996 11a.487.487 0 0 1 .504.496.502.502 0 0 1-.504.504.486.486 0 0 1-.496-.504c0-.143.041-.26.14-.353A.47.47 0 0 1 7.996 11Zm.101-7c.733 0 1.316.19 1.762.59.424.378.641.902.641 1.57 0 .5-.149.935-.435 1.302-.114.134-.423.423-.927.857a2.31 2.31 0 0 0-.537.612 1.522 1.522 0 0 0-.218.813V10h-.915v-.256c0-.367.069-.69.206-.968.16-.334.538-.757 1.156-1.292.183-.178.32-.311.389-.4.228-.279.343-.568.343-.88 0-.445-.138-.79-.39-1.035-.262-.267-.64-.39-1.12-.39-.573 0-.996.178-1.27.546-.252.311-.378.734-.378 1.28H5.5c0-.78.217-1.403.675-1.87C6.633 4.245 7.273 4 8.097 4Z"
                        mask="url(#b)"
                    />
                </g>
            </svg>
        );
    }
}
