// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    NoSetup: typeof import('./src/components/NoSetup.vue')['default']
  }
}

export {}
